aws_region              = "us-east-2"
vpc_name                = "TF-VPC"
vpc_cidr                = "10.0.0.0/16"
public_subnet_cidr      = ["10.0.1.0/24", "10.0.2.0/24"]
private_subnet_k8s_cidr = [ "10.0.3.0/24", "10.0.4.0/24", "10.0.5.0/24" ]
private_subnet_db_cidr  = ["10.0.6.0/24", "10.0.7.0/24", "10.0.8.0/24"]
availability_zones      = ["us-east-1a", "us-east-1b"]
eks_cluster_name        = "TF-eks-cluster"
eks_cluster_role_arn    = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
eks_cluster_role_name   = "TF-cluster-role"
node_group_name         = "TF-node-group"
node_group_min_size     = 1
node_group_max_size     = 3
node_group_desired_size = 2
ec2_ssh_key             = "your-ssh-key-name"
eks_nodegroup_role_name = "TF-nodegroup-role"
